version: '3'
networks:
  backend:
    driver: bridge
services:
  server0:
    build:
      context: .
      dockerfile: ./docker/server0/Dockerfile
    ports:
     - "3000:3000"
    networks:
      - backend
  server1:
    build:
      context: .
      dockerfile: ./docker/server1/Dockerfile
    ports:
     - "3001:3001"
    networks:
      - backend
  server2:
    build:
      context: .
      dockerfile: ./docker/server2/Dockerfile
    ports:
     - "3002:3002"
    networks:
      - backend